import LocalizedStrings from 'react-native-localization';

export const colors = {
    green: '#08DBA5',
    black: '#000000',
    white: '#ffffff',
    grey: 'grey',
    mainBackground: '#0F2635',
    rgba: 'rgba(0, 72, 82, 0.6)',
};

export const ROUTERS = {
    SplashScreen: 'SplashScreen',
    MainScreen: 'MainScreen',
    Registration: 'Registration',
    PlanSelection: 'PlanSelection',
    PickStrength: 'PickStrength',
    KneesProblems: 'KneesProblems',
    StrapDuration: 'StrapDuration',
    ReportScreen: 'ReportScreen',
    ProfileScreen: 'ProfileScreen',
    SignUp: 'SignUp',
    HealthData: 'Health',
    Measuring: 'Measuring',
    Policy: 'Policy',
    Language: 'Language',
    Relaxation: 'Relaxation',
    Reminder: 'Reminder',
    Weight: 'Weight',
    Sound: 'Sound',
    Timer: 'Timer',
    Trening: 'Trening',
};

const titles = new LocalizedStrings({
    "ru": {
        HEADER: 'СБРОСИТЬ ВЕС',
        WARM_UP: 'Разминка',
        GENERAL_SETTINGS: 'Общие настройки',
        SOUND_OPTIONS: 'Голосовые Опции',
        SUPPORT_US: 'Поддержите нас',
        FIRST_WEEK: 'НЕДЕЛЯ 1',
        SECOND_WEEK: 'НЕДЕЛЯ 2',
        THIRD_WEEK: 'НЕДЕЛЯ 3',
        FOURTH_WEEK: 'НЕДЕЛЯ 4',
        FIRST_DAY: '1 - й День',
        SECOND_DAY: '2 - й День',
        THIRD_DAY: '3 - й День',
        FOURTH_DAY: '4 - й День',
        FIFTH_DAY: '5 - й День',
        SIXTH_DAY: '6 - й День',
        SEVENTH_DAY: '7 - й День',
        I_AM: 'Я',
        REPORT: 'Отчёт',
        PLAN: 'План',
        NEWBIE: 'Новичёк',
        CONTINUING: 'Продолжающий',
        ADVANCED: 'Продвинутый',
        OPTIONS_1: '5-10 минут в день',
        OPTIONS_2: '10-20 минут в день',
        OPTIONS_3: '15-30 минут в день',
        CHOOSE_PLAN: 'Выберите Свой План',
        TRAINING_PLAN: 'Худейте с оптимальным планом тренировок',
        NEXT_BUTTON: 'Cледующие',
        I_AM_OK: 'Я в порядке',
        NO_JUMPING: 'Без прыжков',
        LOW_IMPACT: 'Малая ударная нагрузка',
        PROBLEMS_WITH_KNEES: 'У вас есть проблемы с коленями?',
        CHOOSE_HEALTH_PLAN: 'Выберите тренировку по своему состоянию',
        ENTER: 'Вход',
        REGISTRATION: 'Регистрация',
        STRAP_DURATION: 'Сколько Вы можете \n простоять в планке?',
        REGISTRATION_SUB_HEADER: 'Ваши данные помогут нам сделать ваши \n \t\t\t\t\t тренировки эффективнее',
        STRENGTH: 'Сколько раз Вы можете отжаться?',
        LOGIN: 'Вход',
        USERNAME: 'Имя пользователя',
        PASSWORD: 'Пароль',
        CONFIRM_PASSWORD: 'Подтвердите пароль',
        AUTHORIZATION: 'Авторизация',
        PASSWORD_DO_NOT_MATCH: 'Пароли не совпадают',
        REGISTER_ALERT: 'Введите данные',
        PASSWORD_ERROR: 'Не верный пароль или имя пользователя',
        REMINDER: 'Напоминание',
        COUNTDOWN: 'Обратный отсчёт',
        RELAXATION: 'Отдых при тренировке',
        SOUND_SETTINGS: 'Настройки звука',
        SYNCHRONIZATION_GOOGLE: 'Синхронизация с приложением Google',
        HEALTH_DATA: 'Данные о здоровье',
        METRIC_UNITS: 'Метрические единици измерения',
        CHOOSE_LANGUAGE: 'Выбор Языка',
        RESET_RESULT: 'Сбросить результаты',
        SPEECH_TEST: 'Тест речи',
        CHOOSE_SYNTHESIZER: 'Выбрать синтезатор речи TTS',
        DOWNLOAD_SYNTHESIZER: 'Скачать синтезатор речи TTS',
        SOUND_LANGUAGE: 'Голос язык',
        DOWNLOAD_MORE_SYNTHESIZE: 'Скачать больше синтезаторов речи',
        TTS_SETTINGS: 'TTS Настройки устройства',
        SHARE: 'Поделиться с друзьями',
        RATE_US: 'Оцените нас',
        FEED_BACK: 'Отзыв',
        PRIVACY_POLICY: 'Политика конфиденциальности',
        TOTAL: 'Всего',
        HISTORY: 'История',
        WEIGHT: 'Вес',
        TRENING: 'Тренировки',
        CALORIES: 'Ккалории',
        CURRENT: 'Текущий',
        THE_HEAVIEST: 'Самый тяжёлый',
        THE_EASIEST: 'Самый лёгкий',
        BMI: 'ИМТ(кг/м²)',
        HEIGHT: 'Рост',
        EDIT: 'Редактировать',
        DURATION: 'Длительность',
        KG: 'Кг',
        SAVE: 'Сохранить',
        CANSEL: 'Отмена',
        LB: 'lb',
    },
    "en": {
        HEADER: 'Lose Weight',
        WARM_UP: 'Warm up',
        GENERAL_SETTINGS: 'General Settings',
        SOUND_OPTIONS: 'Sound Options',
        SUPPORT_US: 'Support us',
        FIRST_WEEK: 'First week',
        SECOND_WEEK: 'Second week',
        THIRD_WEEK: 'Third week',
        FOURTH_WEEK: 'Fourth week',
        FIRST_DAY: 'First day',
        SECOND_DAY: 'Second day',
        THIRD_DAY: 'Third day',
        FOURTH_DAY: 'Fourth day',
        FIFTH_DAY: 'Fifth day',
        SIXTH_DAY: 'Sixth day',
        SEVENTH_DAY: 'Seventh day',
        I_AM: 'ME',
        REPORT: 'Report',
        PLAN: 'Plan',
        NEWBIE: 'Newbie',
        CONTINUING: 'Continuing',
        ADVANCED: 'Advanced',
        OPTIONS_1: '5-10 минут в день',
        OPTIONS_2: '10-20 минут в день',
        OPTIONS_3: '15-30 минут в день',
        CHOOSE_PLAN: 'Выберите Свой План',
        TRAINING_PLAN: 'Lose weight with an optimal workout plan',
        NEXT_BUTTON: 'Next',
        I_AM_OK: 'I am OK',
        NO_JUMPING: 'Without jumping',
        LOW_IMPACT: 'Low impact',
        PROBLEMS_WITH_KNEES: 'Do you have a problems with knees?',
        CHOOSE_HEALTH_PLAN: 'Choose a workout according to your condition',
        ENTER: 'Enter',
        REGISTRATION: 'Registration',
        STRAP_DURATION: 'How long can you stand in the bar?',
        REGISTRATION_SUB_HEADER: 'Your data will help us make your workouts more effective.',
        STRENGTH: 'How many times can you push out?',
        LOGIN: 'Enter',
        USERNAME: 'Username',
        PASSWORD: 'Password',
        CONFIRM_PASSWORD: 'Confirm password',
        AUTHORIZATION: 'Authorization',
        PASSWORD_DO_NOT_MATCH: 'Passwords do not match',
        REGISTER_ALERT: 'Enter the data',
        PASSWORD_ERROR: 'Invalid password or username',
        REMINDER: 'Reminder',
        COUNTDOWN: 'Countdown',
        RELAXATION: 'Training rest',
        SOUND_SETTINGS: 'Sound settings',
        SYNCHRONIZATION_GOOGLE: 'Synchronization with Google',
        HEALTH_DATA: 'Health data',
        METRIC_UNITS: 'Metric units',
        CHOOSE_LANGUAGE: 'Choose language',
        RESET_RESULT: 'Reset results',
        SPEECH_TEST: 'Speech test',
        CHOOSE_SYNTHESIZER: 'Choose speech synthesizer TTS',
        DOWNLOAD_SYNTHESIZER: 'Download speech synthesizer TTS',
        SOUND_LANGUAGE: 'Sound language',
        DOWNLOAD_MORE_SYNTHESIZE: 'Download more speech synthesizer',
        TTS_SETTINGS: 'TTS Device settings',
        SHARE: 'Share with friends',
        RATE_US: 'Rate us',
        FEED_BACK: 'Feedback',
        PRIVACY_POLICY: 'Privacy policy',
        TOTAL: 'Total',
        HISTORY: 'History',
        WEIGHT: 'Weight',
        TRENING: 'Trenings',
        CALORIES: 'Calories',
        CURRENT: 'Current',
        THE_HEAVIEST: 'The Heaviest',
        THE_EASIEST: 'The easiest',
        BMI: 'BMI(kg/m²)',
        HEIGHT: 'Height',
        EDIT: 'Edit',
        DURATION: 'Duration',
        KG: 'Kg',
        SAVE: 'Save',
        CANSEL: 'Cansel',
        LB: 'lb',
    }
})
export default titles;