export const colors = {
    green: '#08DBA5',
    black: '#000000',
    white: '#ffffff',
    grey: 'grey',
    mainBackground: '#0F2635',
    rgba: 'rgba(0, 72, 82, 0.6)',
};

export const ROUTERS = {
    SplashScreen: 'SplashScreen',
    MainScreen: 'MainScreen',
    Registration: 'Registration',
    PlanSelection: 'PlanSelection',
    PickStrength: 'PickStrength',
    KneesProblems: 'KneesProblems',
    StrapDuration: 'StrapDuration',
    ReportScreen: 'ReportScreen',
    ProfileScreen: 'ProfileScreen',
    SignUp: 'SignUp',
    HealthData: 'Health',
    Measuring: 'Measuring',
    Policy: 'Policy',
    Language: 'Language',
    Relaxation: 'Relaxation',
    Reminder: 'Reminder',
    Weight: 'Weight',
    Sound: 'Sound',
    Timer: 'Timer',
    Trening: 'Trening',
};